/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_eventos_kenny_menjivar;

import java.awt.BorderLayout;

/**
 *
 * @author Kenny
 */
public class Edit_panel extends javax.swing.JPanel {
Deportesedit_panel in;
Banda_musical mu;
    /**
     * Creates new form Edit_panel
     */
    public Edit_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tipoevent = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cantpersonas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        hora = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        minuto = new javax.swing.JComboBox<>();
        Pane = new javax.swing.JPanel();
        refrescar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de Evento:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        tipoevent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deportivo", "Religioso", "Musical" }));
        add(tipoevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del Evento:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, -1, -1));
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 145, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion del Evento:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad de Personas:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, 162, -1));
        add(cantpersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 263, 148, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("Fecha y hora:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 298, -1, -1));
        add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 321, 170, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("Hora:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 298, 52, -1));

        hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "10", "1", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 321, 50, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("Minuto:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 298, -1, -1));

        minuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "59" }));
        add(minuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 321, 70, -1));

        javax.swing.GroupLayout PaneLayout = new javax.swing.GroupLayout(Pane);
        Pane.setLayout(PaneLayout);
        PaneLayout.setHorizontalGroup(
            PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        PaneLayout.setVerticalGroup(
            PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        add(Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        refrescar.setText("Refrescar");
        refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarActionPerformed(evt);
            }
        });
        add(refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 6, -1, 17));
    }// </editor-fold>//GEN-END:initComponents

    private void refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarActionPerformed
        // TODO add your handling code here:
        //Deportivo, Religioso, Musical
        String evento=tipoevent.getSelectedItem().toString();
        if(evento.equals("Deportivo")){
        in = new Deportesedit_panel();
            in.setSize(300,250);
            in.setLocation(0,0);
            Pane.removeAll();
            Pane.add(in,BorderLayout.CENTER);
            Pane.revalidate();
            Pane.repaint(); 
        }else if(evento.equals("Musical")){
        mu = new Banda_musical();
            mu.setSize(300,250);
            mu.setLocation(0,0);
            Pane.removeAll();
            Pane.add(mu,BorderLayout.CENTER);
            Pane.revalidate();
            Pane.repaint(); 
        }
    }//GEN-LAST:event_refrescarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pane;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JTextField cantpersonas;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JComboBox<String> hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> minuto;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton refrescar;
    private javax.swing.JComboBox<String> tipoevent;
    // End of variables declaration//GEN-END:variables
}
