/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_eventos_kenny_menjivar;

import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class Iniciar_Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_Sesion
     */
   Menu_Principal_main mn;
   Puente puente;
    public Iniciar_Sesion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciar_sesion = new javax.swing.JButton();
        Usuario = new javax.swing.JTextField();
        Contra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciar_sesion.setText("Iniciar Sesion");
        iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, 30));
        getContentPane().add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 150, 30));

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, -1));

        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 70, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 250, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_eventos_kenny_menjivar/Imagenes_proyecto_evento/Estadio_Olimpico_pruebo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_sesionActionPerformed
        // TODO add your handling code here:
String username = Usuario.getText(); // Utiliza nombres de variables descriptivos
String password = Contra.getText();
boolean unavez=true;
String name = "haajkl"; // ¿Por qué estás declarando esta variable si no la usas?
String fullName = "vß∆ghv"; // Cambia el nombre de la variable
int age = 87;
String userType = "Admin";

// Supongo que "Puente" es una clase que maneja la autenticación y el acceso a la base de datos de usuarios
Puente puente = new Puente(username, password, name, age, userType);

String storedPassword = puente.contraUser(username); // Almacena la contraseña encontrada
if(username.equals("admin") && password.equals("supersecreto") && unavez){
unavez =false;  
puente.crearUser("Administrador", username, password, 00, "Administrador");
puente.setUserloggin(username);
    puente.actualizardatos(username);
    Menu_Principal_main mn = new Menu_Principal_main();
    mn.setVisible(true);
    this.dispose();
}else if (storedPassword != null && storedPassword.equals(password) && puente.BuscarUser(username)) {
    // Usuario autenticado con éxito
    // puente.setUsuarioLogeado(username); // Comentado por razones desconocidas
    // puente.userlogueado(username); // Comentado por razones desconocidas
    puente.setUserloggin(username);
    puente.actualizardatos(username);
    Menu_Principal_main mn = new Menu_Principal_main();
    mn.setVisible(true);
    this.dispose();
} else if (!puente.BuscarUser(username)) {
    JOptionPane.showMessageDialog(null, "El usuario no existe");
} else if (!storedPassword.equals(password)) {
    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
}
    }//GEN-LAST:event_iniciar_sesionActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar_Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contra;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton iniciar_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
