/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_eventos_kenny_menjivar;

/**
 *
 * @author Kenny
 */
public class Reportes extends javax.swing.JFrame {
    Menu_Principal_main menu;
    Lista_eventos_realizados LER;
    Listar_eventos_futuros LEF;
    Listar_Eventos_Cancelados LEC;
    Ingreso_fecha IF;
    Informacion_user VPU;
    /**
     * Creates new form Administradodr_usuarios
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Listar_eventos_realizados = new javax.swing.JButton();
        Listar_eventos_futuros = new javax.swing.JButton();
        Listar_eventos_cancelados = new javax.swing.JButton();
        Ingreso_generado_por_fecha = new javax.swing.JButton();
        Ver_Perfil_del_usuario = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Reportes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 250, 40));

        Listar_eventos_realizados.setText("Listar eventos realizados");
        Listar_eventos_realizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_eventos_realizadosActionPerformed(evt);
            }
        });
        getContentPane().add(Listar_eventos_realizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        Listar_eventos_futuros.setText("Listar eventos futuros");
        Listar_eventos_futuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_eventos_futurosActionPerformed(evt);
            }
        });
        getContentPane().add(Listar_eventos_futuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        Listar_eventos_cancelados.setText("Listar eventos cancelados");
        Listar_eventos_cancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_eventos_canceladosActionPerformed(evt);
            }
        });
        getContentPane().add(Listar_eventos_cancelados, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        Ingreso_generado_por_fecha.setText("Ingreso generado por fecha");
        Ingreso_generado_por_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_generado_por_fechaActionPerformed(evt);
            }
        });
        getContentPane().add(Ingreso_generado_por_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        Ver_Perfil_del_usuario.setText("Ver Perfil del usuario");
        Ver_Perfil_del_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_Perfil_del_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Ver_Perfil_del_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        Back.setText("Regresar a Menú Principal");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        menu= new Menu_Principal_main();
        menu.setVisible(true);
        this.dispose();
               
    }//GEN-LAST:event_BackActionPerformed

    private void Listar_eventos_realizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_eventos_realizadosActionPerformed
        // TODO add your handling code here:
        LER = new Lista_eventos_realizados();
        LER.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Listar_eventos_realizadosActionPerformed

    private void Listar_eventos_futurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_eventos_futurosActionPerformed
        // TODO add your handling code here:
        LEF = new Listar_eventos_futuros();
        LEF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Listar_eventos_futurosActionPerformed

    private void Listar_eventos_canceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_eventos_canceladosActionPerformed
        // TODO add your handling code here:
        LEC = new Listar_Eventos_Cancelados();
        LEC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Listar_eventos_canceladosActionPerformed

    private void Ingreso_generado_por_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_generado_por_fechaActionPerformed
        // TODO add your handling code here:
        IF = new Ingreso_fecha();
        IF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ingreso_generado_por_fechaActionPerformed

    private void Ver_Perfil_del_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_Perfil_del_usuarioActionPerformed
        // TODO add your handling code here:
        VPU= new Informacion_user();
        VPU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ver_Perfil_del_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Ingreso_generado_por_fecha;
    private javax.swing.JButton Listar_eventos_cancelados;
    private javax.swing.JButton Listar_eventos_futuros;
    private javax.swing.JButton Listar_eventos_realizados;
    private javax.swing.JButton Ver_Perfil_del_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
